name: Maven PR Build

# We require all commits go through PR on GitHub
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Maven PR Builder (JDK ${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17, 21 ]
        maven: [ 3.8.6 ]
        jdk: [ temurin ]
    steps:
      - name: Check out source code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@860f60056505705214d223b91ed7a30f173f6142 # v3.3.0
        with:
          cache: maven
          distribution: ${{ matrix.jdk }}
          java-version: ${{ matrix.java }}
      - name: Set up Maven
        uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
        with:
          maven-version: ${{ matrix.maven }}
      - name: Build with Maven
        run: |
          mvn -V --no-transfer-progress --batch-mode \
          -DlogLevel=DEBUG -DtestLogLevel=DEBUG \
          -Dorg.slf4j.simpleLogger.log.net.sourceforge.pmd=error \
          -Pdefault clean verify
